import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className="flex min-h-screen max-h-screen flex-col">
          <header>
            <nav className="bg-white border-gray-400 px-4 lg:px-6 py-3 border-b">
              <div className="flex flex-wrap mx-auto max-w-screen-xl">
                <div className="flex items-center">
                  <img src="./Vultron.svg" alt="Logo" className="h-8 w-8" />
                  <h1 className="text-lg font-semibold ml-2">VultGPT 1.0</h1>
                </div>
              </div>
            </nav>
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
